name: Deploy Playground
on:
  push:
    tags:
      - "playground-[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - name: Build
        run: |
          npm install
          npm run build
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.otf'
          out-file-path: 'playground/public'
      - run: |
          mv playground/public/*.otf playground/public/FBKINGDOM-FONT.otf
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './playground/public'
      - uses: actions/deploy-pages@v4
